<?php

return [
    'Colombo',
    'Dehiwala-Mount Lavinia',
    'Moratuwa',
    'Sri Jayawardenepura Kotte',
    'Negombo',
    'Kandy',
    'Kalmunai',
    'Vavuniya',
    'Galle',
    'Trincomalee',
    'Batticaloa',
    'Jaffna',
    'Katunayake',
    'Dambulla',
    'Kolonnawa',
    'Anuradhapura',
    'Ratnapura',
    'Badulla',
    'Matara',
    'Puttalam',
    'Kegalle',
    'Chilaw',
    'Matale',
    'Kalutara',
    'Beruwala',
    'Embilipitiya',
    'Mannar',
    'Kurunegala',
];
